### ISSUE TITLE
单从结果看好像没有排名第一的好唉

### ISSUE THREAD

**Issue by eyuansu62** [thunlp/KernelGAT#1]
单从结果看好像没有排名第一的好唉

**Comment by EdwardZH** [comment]
是的，我们是7月左右做出来的结果，我们是BERT base中最好的结果，排名第一的pipline整个都变化了，所以不太好说到底是哪里的作用。我们更多的是想做一个更通用的推理模型，从而能够适用于更多任务。感谢你的关注。

**Comment by eyuansu62** [comment]
也感谢您的回复，其实我从GEAR文章就再看你们组的任务，也看了排名第一的文章，确实整个架构都不太一样，自己是一个刚准备读研的学生，还希望能和您多学习，嘿嘿，也能从您们身上找点可以做的地方。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"EdwardZH"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月23日(星期三) 晚上8:03
收件人:&nbsp;"thunlp/KernelGAT"<KernelGAT@noreply.github.com&gt;;
抄送:&nbsp;"末冬末秋"<772468951@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [thunlp/KernelGAT] 单从结果看好像没有排名第一的好唉 (#1)




是的，我们是7月左右做出来的结果，我们是BERT base中最好的结果，排名第一的pipline整个都变化了，所以不太好说到底是哪里的作用。我们更多的是想做一个更通用的推理模型，从而能够适用于更多任务。感谢你的关注。

**Comment by EdwardZH** [comment]
欢迎交流，排名top2的两个模型确实有值得借鉴的地方，只不过我们是想用更简单高效的方法来建模，同时为了可复现性我们也没有特别的调参，希望能够带给学术界一些不一样的insight。

**Comment by eyuansu62** [comment]
今天还在询问老师，老师也说第一那种方法工程太大了，祝你们加油，嘿嘿，以后有问题还希望能多指教！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"EdwardZH"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月23日(星期三) 晚上8:10
收件人:&nbsp;"thunlp/KernelGAT"<KernelGAT@noreply.github.com&gt;;
抄送:&nbsp;"末冬末秋"<772468951@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [thunlp/KernelGAT] 单从结果看好像没有排名第一的好唉 (#1)




欢迎交流，排名top2的两个模型确实有值得借鉴的地方，只不过我们是想用更简单高效的方法来建模，同时为了可复现性我们也没有特别的调参，希望能够带给学术界一些不一样的insight。

**Comment by EdwardZH** [comment]
好的 感谢你的关注 也希望以后多交流
