### ISSUE TITLE
关于CorefBERT预训练模型参数。

### ISSUE THREAD

**Issue by yangxia605** [thunlp/KernelGAT#13]
您好：
首先非常感谢您分享代码并且有这么出色的工作。
我是从Document level的关系抽取找到这个仓库的，我想请问一下我在哪里获取CorefBERT 的训练参数，并且我能基于这些参数进行text的embedding，然后在下游任务中做一些模型设计吗/
再次感谢！！！

**Comment by yangxia605** [comment]
paper是这篇：Coreferential Reasoning Learning for Language Representation

**Comment by EdwardZH** [comment]
hi，感谢你的认可。首先你可以先尝试使用RoBRERTa large和electra来实现，关于corefBERT这篇文章，我们也在投关于checkpoint的相关信息你可以发邮件给Deming Ye如果需要帮助的话也可以email我。

**Comment by yangxia605** [comment]
好的，非常感谢。我先和Deming Ye沟通试试。也祝您投稿顺利！
