### ISSUE TITLE
process.sh is missing under retrieval_model/

### ISSUE THREAD

**Issue by jacklxc** [thunlp/KernelGAT#16]
process.sh is supposed to be under retrieval_model/ as the README indicates, but it's missing. Can you please add it back? It will be great if you also provide the output of your document retrieval output. Thank you!

**Comment by EdwardZH** [comment]
The process.sh is used to generate training pairs for retrieval models. As we have described you should go to the data folder and run it.

**Comment by EdwardZH** [comment]
The process.sh is used to generate training pairs for retrieval models. As we have described you should go to the data folder and run it.

**Comment by EdwardZH** [comment]
I will close this issue. If you have problems, you can open a new one.
