### ISSUE TITLE
Typo in the original paper

### ISSUE THREAD

**Issue by jacklxc** [thunlp/KernelGAT#18]
I found the equation (8) of the paper Kernel Graph Attention Network for Fact Verification has a non-trivial typo: there should be a square in the numerator term to avoid a positive value passing into the exponential function, just like the original paper Xiong et al. 2017.

**Comment by EdwardZH** [comment]
Please refer to our final version https://www.aclweb.org/anthology/2020.acl-main.655.pdf.
