### ISSUE TITLE
all_train/all_dev疑惑

### ISSUE THREAD

**Issue by chenhch8** [thunlp/KernelGAT#19]
作者您好，我想问下，`all_train.json`和`all_dev.json`是不是就是由document retrieval输出的候选文档集，也就是您文中说是来于GEAR？

**Comment by EdwardZH** [comment]
他是有两步，第一步document retrieval跟GEAR一样使用entity linking类似方法，第二步则是sentence retrieval，这里用的BERT的结果，也就是把第一步得到的句子重排序，你提到这两个文件都是经过两步之后得到的结果。

**Comment by EdwardZH** [comment]
没有其他问题的话这个issue我就关掉了

**Comment by Haelles** [comment]
> 他是有两步，第一步document retrieval跟GEAR一样使用entity linking类似方法，第二步则是sentence retrieval，这里用的BERT的结果，也就是把第一步得到的句子重排序，你提到这两个文件都是经过两步之后得到的结果。

作者您好，请问按照您所说，all_train.json是经过sentence retrieval的结果，那为什么还要在retrieval_model/中使用all_train.json中对BERT进行训练呢？我猜测all_train.json仅仅是对GEAR的document retrieval结果添加了golden evidence？

**Comment by EdwardZH** [comment]
是的 当时处理时候觉得没有证据的话会造成标签偏移 其实也可以不用
