### ISSUE TITLE
请问实验运行环境包括版本这个有吗

### ISSUE THREAD

**Issue by cucumberpieces** [thunlp/KernelGAT#20]

**Comment by EdwardZH** [comment]
对于kgat可以自行修改代码适配到最新的transformers，在kgat模型中需要传入预训练模型即可，由于transformers工具包更新太快我们实验采用环境应该是pytorch_pretrained_bert，pytorch3.6

**Comment by cucumberpieces** [comment]
> 对于kgat可以自行修改代码适配到最新的transformers，在kgat模型中需要传入预训练模型即可，由于transformers工具包更新太快我们实验采用环境应该是pytorch_pretrained_bert，pytorch3.6

现在的是torch和cuda的版本有问题

**Comment by EdwardZH** [comment]
torch 和cuda的版本匹配请参考pytorch官网。https://pytorch.org

**Comment by cucumberpieces** [comment]
> torch 和cuda的版本匹配请参考pytorch官网。https://pytorch.org

请问我的是torch1.1.0版本，报这个异常bool这里如何修改
KernelGAT/KernelGAT-master/kgat/models.py", line 120, in get_intersect_matrix_att
    log_pooling_sum = log_pooling_sum.masked_fill_((1 - attn_q).bool(), -1e4)
AttributeError: 'Tensor' object has no attribute 'bool'

**Comment by EdwardZH** [comment]
.bool()改成.byte()

**Comment by cucumberpieces** [comment]
> .bool()改成.byte()

正常执行kgat/test.sh 需要执行多久，改成了.byte()之后，不报错了，感觉跑很久
