### ISSUE TITLE
想请教一下论文中的一个问题

### ISSUE THREAD

**Issue by jun0wanan** [thunlp/KernelGAT#22]
你好，

  非常抱歉打扰作者，感谢你开源你的代码！我是cv方向的新手，因为你的这个图感觉很有意思，便也学习了一番，但是有个地方可能因为我之前不了解这个任务，我有一些不理解，Token Level Attention 和 Sentence Level Attention 是为什么要设计两个呢？莫非是因为这个evidence图是同时有 词 的节点也有句子的节点吗？希望得到你的回答！感谢(●'◡'●)

jun0

**Comment by EdwardZH** [comment]
因为在推理中每个证据中只有一部分词语起到事实验证作用，所以我们设计了Kernel attetnion使得模型更好的focus在一些重要的词语上，进一步fine-grain我们的证据节点的表示，后面应用正常图神经网络来整合证据信息类似gear，因此是一个层次化注意力机制。

**Comment by jun0wanan** [comment]
> 因为在推理中每个证据中只有一部分词语起到事实验证作用，所以我们设计了Kernel attetnion使得模型更好的focus在一些重要的词语上，进一步fine-grain我们的证据节点的表示，后面应用正常图神经网络来整合证据信息类似gear，因此是一个层次化注意力机制。

感谢你的回复！那是不是每个node都是一开始是一句话（evidence）呢？不是词语与句子的混合node

**Comment by EdwardZH** [comment]
是的，每一个节点是claim拼接evidence然后bert得到每个token表示，我们论文中是抽象成一个节点这样。

**Comment by EdwardZH** [comment]
如果没有问题我就close了

**Comment by jun0wanan** [comment]
> 是的，每一个节点是claim拼接evidence然后bert得到每个token表示，我们论文中是抽象成一个节点这样。

谢谢作者！
