### ISSUE TITLE
Missing files? 

### ISSUE THREAD

**Issue by Yibing-Du** [thunlp/KernelGAT#24]
Hi there! Maybe I'm confused but I don't see ./rationale_selection/transformer.py or ./kgat/test.py for scikgat. Would you mind kindly letting me know where they are?

**Comment by EdwardZH** [comment]
For these files please refer to https://github.com/allenai/scifact, we use the same rationale selection models. I can also update these files later.

**Comment by Yibing-Du** [comment]
Hi Edward! Thank you for your swift reply. Just to confirm, is ./rationale_selection/transformer.py the same as https://github.com/allenai/scifact/blob/master/verisci/inference/rationale_selection/transformer.py? For ./kgat/test.py, I'm assuming it'll differ from the one in kgat folder because the two train.py files seem to be different. Would you mind kindly uploading it?

**Comment by EdwardZH** [comment]
These files are same because we use the same rationale selection models. I will upload them later.

**Comment by EdwardZH** [comment]
Hi I have updated this file. If you have other questions, you can also propose issues. Best wishes.

**Comment by Yibing-Du** [comment]
Thanks a lot!

**Comment by Yibing-Du** [comment]
Following up - Would you mind uploading ./scikgat/kgat/test.py? It's probably not the same as ./kgat/test.py because the expected arguments are different. Thanks again!

**Comment by EdwardZH** [comment]
Hi, I have updated the test.py file. This file is the same as the kgat one.
