### ISSUE TITLE
pretraining the BERT-concat

### ISSUE THREAD

**Issue by Jason98Xu** [thunlp/KernelGAT#29]
Hi,
I came across a problem when I tried to pretrain BERT-concat. The problem is that the file train.sh in pretrain folder utilize all_train.json to pretrain the BERT for claim verification stage. I guess that should be bert_train.json since it is the results after evidence selection stage. Is my understanding wrong?

Looking forward to your reply!

**Comment by EdwardZH** [comment]
Our pretraining (continuous training) codes inherit from the sentence reranking part. Thus, it uses the pairwise loss to train BERT with the evidence relevance relation. If you use bert_train.json, It's more like training on the fact verification task.

**Comment by Jason98Xu** [comment]
Thanks for your prompt reply. So is the checkpoint of pretrained BERT based on evidences before sentence selection stage (the second stage)?  From this view, the label during pretraining indicates whether an evidence is relevant to a claim but not whether an evidence can support a claim. Is it right?

**Comment by EdwardZH** [comment]
You are right.
