### ISSUE TITLE
Explaination of dataset

### ISSUE THREAD

**Issue by tingkai-zhang** [thunlp/KernelGAT#3]
Hi, congrats on your awesome work.

Can you please write more stuff in the readme to add some description about the input data and output of the pipeline?

Also can you tell me what is the number following each string means in this example? What does 1 and 0 here means? Why are these two strings grouped together?
`
["Soul_Food_-LRB-soundtrack-RRB-", 1, "It was released on September 16 , 1997 through LaFace Records and mainly consisted of RB music with a bit of some hip hop .", 0]
`
(This example is clipped from a line in `all_dev.json`)

Thank you!

**Comment by EdwardZH** [comment]
Hello! The all_train.json and all_dev.json are the original file, which contains all wikipage sentences. For the case ["Soul_Food_-LRB-soundtrack-RRB-", 1, "It was released on September 16 , 1997 through LaFace Records and mainly consisted of RB music with a bit of some hip hop .", 0], 0 and 1 indicate if it is the golden evidence sentence. I will continue to complete the Code readme.

**Comment by tingkai-zhang** [comment]
Excellent. Thanks.
