### ISSUE TITLE
Question about the proportion of single and multiple evidence

### ISSUE THREAD

**Issue by MrSeven77** [thunlp/KernelGAT#30]
Hi,
In the paper the author mentioned for the golden evidence:

> The single evidence reasoning set and the multiple evidence reasoning set contain 11,372 (85.3%) and 1,960 (14.7%) instances, respectively.

However, when I preprocess the _golden_train.json_ and _golden_dev.json_, it turns out that in the dev set there are 9,766 with single evidence and 3,566 with multiple evidence. The ratio is similar in the training set. But both of them do not match the statistics in the paper. 

Could you please explain why?

**Comment by EdwardZH** [comment]
The data splits are according to golden annotations.

**Comment by MrSeven77** [comment]
Yeah, aren't _golden_train.json_ and _golden_dev.json_ the golden annotations?
Or am I preprocessing wrong files?

**Comment by EdwardZH** [comment]
I do not know how you process the file. In fact, the partition depends on whether the evidence set has one more evidence.
