### ISSUE TITLE
performance on different scenarios

### ISSUE THREAD

**Issue by wonderlandais** [thunlp/KernelGAT#31]
您好，请问可以提供下single-evidence和multiple-evidence集合吗？

**Comment by wonderlandais** [comment]
因为想参照您table4的实验。谢谢！

**Comment by EdwardZH** [comment]
You can follow the process code below:
import json

def process_file(inpath, outpath):
    with open(inpath) as f:
        with open(outpath + "_multi.json", "w") as out_multi, open(outpath + "_single.json", "w") as out_single:
            for line in f:
                data = json.loads(line)
                if data["verifiable"] != "NOT VERIFIABLE":
                    flag = False
                    for evidence in data["evidence"]:
                        if len(evidence) > 1:
                            flag = True
                    if flag:
                        out_multi.write(line)
                    else:
                        out_single.write(line)

if __name__ == "__main__":
    process_file("dev.jsonl", "dev")

**Comment by EdwardZH** [comment]
If you want the final data, you can email me.

**Comment by wonderlandais** [comment]
问题已解决感谢您的解答！
