### ISSUE TITLE
Document retrieval

### ISSUE THREAD

**Issue by Raldir** [thunlp/KernelGAT#33]
Dear authors,

I am currently attempting to replicate the retrieval results on the dev set and was wondering whether you could provide additional details how `all_dev.jsonl` was generated. As far as I understood it, this file consists of retrieved documents, following the methodology of GEAR (which uses the same document retriever as  Athene UKP TU Darmstadt). However, I am not able to replicate the document retrieval results, using the exact same scripts of GEAR. In fact, while I get a recall@5 0.8144 and recall@100 of 0.9007 (which aligns with their reported scores), with `all_dev.jsonl` I get a recall of 0.8911 and 1.000, respectively. I think I am missing something. If possible could you share the script on how the file was generated?

Thank you for your help!

**Comment by Haelles** [comment]
> For dev and train files, we add golden documents in them to alleviate the influence of the document retrieval part. I have tested our all_test.jsonl file, it is the same with GEAR retrieved data. Thw original dev and test files are here (https://drive.google.com/drive/folders/1hKuxUu_ecSIVqaeZaBOfMaquNgdBE1yU?usp=sharing). I also find that the document retrieval files of GEAR and UKP are not almost the same.

Hi, thanks for your great work! I find that the google drive link is broken. Could you please have a look at it?

**Comment by EdwardZH** [comment]
I have renewed the link access. You can try again.
