### ISSUE TITLE
a bug?

### ISSUE THREAD

**Issue by eyuansu62** [thunlp/KernelGAT#4]
when I run train.sh in retrieval_model, it happens some errors:
 File "/home/q/Downloads/KernelGAT-master/retrieval_model/data_loader.py", line 131, in read_file
    examples.append([self.process_sent(sublines[0]), self.process_sent(sublines[2]),self.process_sent(sublines[4])])
IndexError: list index out of range
it looks like happening in the dataloader function in data_loader.py.

**Comment by EdwardZH** [comment]
I have updated my codes. I miss some codes and readme.

**Comment by eyuansu62** [comment]
thanks a lot
