### ISSUE TITLE
where is the train.json

### ISSUE THREAD

**Issue by eyuansu62** [thunlp/KernelGAT#5]
Excuse me,
 i find an issue that it needs train.json in train.sh of pretrain folder, which --train_path ../data/pretrain/train.json \, but the data folder you provide in Google Drive does not contain this file. where can i get this file?
Thanks a lot for your reply.

**Comment by EdwardZH** [comment]
I feel sorry about bugs, I am a little busy because of the ACL ddl. I fixed the bug.

**Comment by eyuansu62** [comment]
no, it is my sorry. I can wait after acl and hope you can success. best wishes.------------------ 原始邮件 ------------------
发件人: "EdwardZH"<notifications@github.com>
发送时间: 2019年10月30日(星期三) 晚上7:50
收件人: "thunlp/KernelGAT"<KernelGAT@noreply.github.com>;
抄送: "eyuansu62"<772468951@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [thunlp/KernelGAT] where is the train.json (#5)



I feel sorry about bugs, I am a little busy because of the ACL ddl. I fixed the bug.
 
&mdash;

**Comment by EdwardZH** [comment]
Thanks a lot. If you find other problems, please contact me, I will fix them quickly.
