### ISSUE TITLE
Error when running on multiple gpus

### ISSUE THREAD

**Issue by tingkai-zhang** [thunlp/KernelGAT#6]
Hi, when running kgat model, it will have cuda device error when `self.mu` or `self.sigma` and `sim` are on different gpu devices.
Initilize `self.mu` and `self.sigma` with `.cuda()` is not enough since it does not guarantee the variables in `forward()` are on the same device.
Currently I just move these variables in `forward()`, but I wonder if you would give a better solution.

**Comment by EdwardZH** [comment]
Hello tingkai, I guess you have some problems with multi-gpu training. Hence I have updated codes to fit multi GPU. I have done more experiments on different pre-trained models, I will publish them later.

**Comment by EdwardZH** [comment]
Hello, I have updated a new version code. I will close this issue. Thanks for your attention.
