### ISSUE TITLE
golden evidence

### ISSUE THREAD

**Issue by chenchonghao** [thunlp/KernelGAT#7]
Sorry, may be i don't  understand your bert retrieval. but where are your golden evidence comes from,  whether you use the dev_share_task 's evidences as golen evidence? if you add golden evidences in bert_dev, the dev score and accuracy seems   meaningless，because you use the true evidence，not retrieve evidence. 
looking forward your answer, thank you  very much!

**Comment by EdwardZH** [comment]
We use the annotated evidence as golden evidence and other evidence from retrieved documents is regarded as negative ones. Both training and development sets have golden evidence. For BERT retrieval, golden labels of development can not be seen in training process. I do not know if I explain clearly and I think you can describe your question more clearly.

**Comment by chenchonghao** [comment]
不好意思，我可能用中文能够更清晰的表达我的意思。是这样的，因为我发现验证集的准确率和FEVER得分都偏高于测试集，所以我想问一下如果您使用bert retrieval 得到最后bert_dev 证据集是由annotated evidence 和 retrieved evidences组成的，那不是相当于将正确的证据集放到了其中吗？如果是这样的话验证集的结果不就相当于看到答案再做出判断吗？
不知道您能否明白我的意思，期待收到您的回复，非常感谢！

**Comment by EdwardZH** [comment]
首先，第一个，验证集准确率高了很多我觉得这个是正常的，因为我们在做retrieval时候用的dev集合来判断何时停止训练，因此在dev可能会高一些，这个也是实验结果导致。你说的这个应该是在claim verification阶段，这个阶段我们将golden evidence全部引入training和dev集合上，一个则与baseline GEAR一致，另外我认为这个也是合理的，因为没有足够的evidence的话预测标签则会偏移到Not enough info。我们在dev集合测试的时候是不加golden evidence的，因此你可以看到evidence的准确率虽然很高但并不为1。看到答案再判断标签我认为也是有其合理性，就像我之前提到过的预测标签偏移，因为我们都是按照FEVER score来评测，所以我们在训练过程中希望能够根据证据进行判断，并不需要刻意的拟合LA。另外我们提供了ESIM的结果，也是希望能够让大家在多个不同的retrieval场景下检验模型效果并不是仅仅去看谁高谁低。

**Comment by EdwardZH** [comment]
首先，第一个，验证集准确率高了很多我觉得这个是正常的，因为我们在做retrieval时候用的dev集合来判断何时停止训练，因此在dev可能会高一些，这个也是实验结果导致。你说的这个应该是在claim verification阶段，这个阶段我们将golden evidence全部引入training和dev集合上，一个则与baseline GEAR一致，另外我认为这个也是合理的，因为没有足够的evidence的话预测标签则会偏移到Not enough info。我们在dev集合测试的时候是不加golden evidence的，因此你可以看到evidence的准确率虽然很高但并不为1。看到答案再判断标签我认为也是有其合理性，就像我之前提到过的预测标签偏移，因为我们都是按照FEVER score来评测，所以我们在训练过程中希望能够根据证据进行判断，并不需要刻意的拟合LA。另外我们提供了ESIM的结果，也是希望能够让大家在多个不同的retrieval场景下检验模型效果并不是仅仅去看谁高谁低。

**Comment by chenchonghao** [comment]
首先，非常感谢您能及时的回复！关于gear，它应该是在训练集中将正确的答案放了进去，验证集应该是只用的检索出来的证据。我有疑问的点就是在于验证集中是否不应该放入正确答案，模型的dev结果应该是只使用retrieval的证据才能说明你bert retrieval 的效果，我不知道是不是我没有理解清楚您的意思， 还有您提到dev集合测试没有加golen evidnece？不好意思我没有特别理解这个意思，您不是提到您加入golden evidence在dev中吗？
期待您的回复！非常感谢您！！

**Comment by EdwardZH** [comment]
没有加呀，只是在训练时候的dev集合上面加了golden。在测试阶段只用到了retrieved evidence。

**Comment by chenchonghao** [comment]
不好意思，是我没有仔细看清楚您的代码。我误把您提供的云盘中的bert_dev 当做直接放入golden_evidence得到的了。我想问一下您云盘中的bert_dev应该是测试时使用的证据，那这个又是怎么得到的？期待您的再一次回复，谢谢！

**Comment by EdwardZH** [comment]
我都说过了 测试时候是BERT retrieval直接得到的 我上面已经详细的说明了

**Comment by chenchonghao** [comment]
哦哦好的，真的非常感谢您的耐心回复！
